FROM node:22-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN apk add --no-cache openssl
RUN npm install

# Copy prisma schema
COPY prisma ./prisma

# Generate Prisma Client (needed for migration engine)
RUN npx prisma generate

CMD ["sh", "-c", "npx prisma migrate deploy"]
